FROM office-registry-vpc.cn-hongkong.cr.aliyuncs.com/base/ubuntu:22.04


# RUN apt-get update -y && \
#     apt-get install -y git jq curl wget && \
#     curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

